hydra:
  run:
    dir: outputs/${hydra:job.config_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true

train:
  seed: 1000
  deterministic: false
  rlimit_nofile: 1048576
  resume: null

  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${hydra:runtime.output_dir}
    name: tb
    version: null
    default_hp_metric: false

  logger_layout:
    add_custom_scalars: true
    iou_thresholds: [0.50, 0.40, 0.30, 0.20, 0.10, 0.01]

  # optional: override defaults
  monitor: "Validation/Masks/mAP"
  monitor_mode: "max"
  save_top_k: 3
  save_last: true
  ckpt_filename: "best_{epoch}-{step}"
  ckpt_every_n_epochs: 1
  lr_logging_interval: "step"

  # DDP defaults (used if train.strategy not provided)
  ddp_backend: "nccl"
  find_unused_parameters: true

  trainer:
    accelerator: gpu
    devices: [1]
    precision: bf16-mixed
    max_epochs: 30
    gradient_clip_algorithm: norm
    gradient_clip_val: 0.5
    accumulate_grad_batches: 2
    num_sanity_val_steps: 5
    check_val_every_n_epoch: 10
    log_every_n_steps: 10
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    enable_progress_bar: true
    enable_model_summary: true

model:
  forward_chunk_size: 16
  max_mask_to_train: 384

  backbone:
    _target_: condinst3d.arch.backbone.unetr_specific_mod.UNetRSpecificMod

    specific_modality_index: 3
    in_channels: 4
    filters: [ 32, 64, 96, 128, 192, 256 ]
    kernels: [ [ 3,3,1 ],[ 3,3,3 ],[ 3,3,3 ],[ 3,3,3 ],[ 3,3,3 ],[ 3,3,3 ] ]
    strides: [ [ 1,1,1 ],[ 2,2,1 ],[ 2,2,2 ],[ 2,2,2 ],[ 2,2,2 ],[ 2,2,1 ] ]
    head_start_index: 2
    heads_dim: 128
    out_channels: 8

  matcher:
    num_candidates: 9
    min_pos: 3
    threshold_strategy: "topk"
    center_in_gt: true
    anchors_sizes: [ [ 4,4,2 ], [ 8,8,4 ], [ 16,16,8 ], [ 32, 32, 8 ] ]

  heads:
    classification:
      num_classes: 1
      prior_probability: 0.01

    instance_segmentation:
      channels: 8
      num_layers: 3
      kernel_size: 1
      size_of_interest: 4

    controller:
      num_layers: 2

  losses:
    classification:
      _target_: monai.losses.FocalLoss
      to_onehot_y: false
      use_softmax: false
      gamma: 2.0
      alpha: 0.25
      reduction: "none"

    instance_segmentation:
      _target_: monai.losses.DiceFocalLoss
      to_onehot_y: false
      sigmoid: true
      gamma: 2.0
      lambda_dice: 1.0
      lambda_focal: 1.0
      reduction: "mean"

    semantic_segmentation:
      _target_: monai.losses.DiceFocalLoss
      include_background: false
      to_onehot_y: true
      softmax: true
      gamma: 2.0
      lambda_dice: 1.0
      lambda_focal: 1.0
      reduction: "mean"

  inference:
    mask_thresh: 0.5
    score_thresh: 0.5
    nms_thresh: 0.5
    group_thresh: 0.5
    topk_candidates: 20

  evaluation:
    iou_list: [ 0.01, 0.1, 0.2, 0.3, 0.4, 0.5 ]
    ap_n_interp: 11

  visualization:
    img_channels: ['t1w', 't2w', 'flr', 'freqmap']
    channel_seg_under_image: 3
    crop_size: [96, 96]
    show_slices: [-1, 0, 1]
    figsize: 1.5
    num_images_to_show: 16

  optim:
    optimizer:
      _target_: torch.optim.AdamW
      lr: 1e-3
      weight_decay: 1e-4

    scheduler:
      _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: 1000
      eta_min: 1e-6

    scheduler_cfg:
      interval: epoch
      frequency: 1
      name: lr

data:
  root_path: "/scratch/04/public_datasets/nnDet/Task100_PRL"
  fold: 0
  modalities: ['t1w', 't2w', 'flr', 'freqmap']
  splits_path: "/scratch/04/public_datasets/nnDet/Task100_PRL/preprocessed/splits_final.pkl"
  num_workers:
    train: 24
    val: 24
    test: 1
  batch_size:
    train: 2
    val: 1
    test: 1

  empty_case_weight: 0.2
  instance_weight_power: 0.7

  patch_size: [128, 128, 48]
  patches_per_subject: 2
  patch_overlap: 0.5
  spatial_augmentation_prob: 0.25
  intensity_augmentation_prob: 0.25
